version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=hackergame
      - POSTGRES_PASSWORD=hackergame
    volumes:
      - ./data/hackergame_db_data:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./data/hackergame_static_data:/var/opt/hackergame
      - ./data/hackergame_django_log_data:/var/log/django
    restart: always
  nginx:
    image: nginx
    ports:
      - "11111:80"
    volumes:
      - ./conf/nginx-sites/docker:/etc/nginx/conf.d/default.conf:ro
      - ./data/hackergame_log_data:/var/log/nginx
      - ./data/hackergame_static_data:/var/opt/hackergame
    depends_on:
      - web
    restart: always
